#!/bin/bash

###############################################################################
# General                                                                     #
###############################################################################
alias l="ls"
alias la="ls -al"

alias ip="dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com"

###############################################################################
# Git                                                                         #
###############################################################################
alias g="git"
alias gc="git commit"
alias gcam="git add -A && git commit -am"  # Commit all changed files with message
alias gcaa="git add -A && git commit -a --amend --reuse-message=HEAD"  # Add all changed files to head commit
alias gd="git diff"
alias gds="git diff --name-only | xargs"  # Short git diff (file names only)
alias gl="git log --graph --all --pretty=format:'%C(yellow)%h -%C(auto)%d %C(bold cyan)%s %C(bold white)(%cr)%Creset %C(dim white)<%an>'"  # Compressed graph log format
alias gp="git push"
alias gs="git status"
alias gss="git status -s"  # Short git status

# Delete all remote tracking Git branches where the upstream branch has been deleted
alias git_prune="git fetch --prune && git branch -vv | grep 'origin/.*: gone]' | awk '{print \$1}' | xargs git branch -d"

###############################################################################
# Web search                                                                  #
###############################################################################
alias google='web_search google'
alias ddg='web_search duckduckgo'
alias sp='web_search startpage'
alias github='web_search github'

# bangs
alias wiki='web_search duckduckgo \!w'
alias news='web_search duckduckgo \!n'
alias youtube='web_search duckduckgo \!yt'
alias map='web_search duckduckgo \!m'
alias image='web_search duckduckgo \!i'
alias ducky='web_search duckduckgo \!'
